### ISSUE TITLE
Laravel 9 missing on packagist (failed deploy?)

### ISSUE THREAD

**Issue by joelharkes** [beyondcode/laravel-mailbox#105]
Hi

it looks like it failed to deploy the proper dependencies for Laravel 9: https://packagist.org/packages/beyondcode/laravel-mailbox

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/2960938/169060605-346fa71d-0acf-4683-bfd8-e10cd2a9f700.png">

even though your code in repo suggests 9.0 is allowed: https://github.com/beyondcode/laravel-mailbox/blob/master/composer.json

<img width="435" alt="image" src="https://user-images.githubusercontent.com/2960938/169060863-d5cc9795-93fb-4330-8967-1d4620fa22a0.png">

could you try a re-deploy?

**Comment by yehuda-hybiz** [comment]
@joelharkes Thanks!

**Comment by gizburdt** [comment]
@mpociot Could you please tag a new version, so we can use it in composer? Thanks! :)

**Comment by lazer-hybiz** [comment]
👀

**Comment by jeverington** [comment]
+1

**Comment by clementmas** [comment]
I know this is open-source and I understand if there's a delay to support newer Laravel versions. A few weeks or months, ok. But Laravel 9 came out more than 6 months ago.

A lot of us are held back by this package. I think you should either archive it or maintain it.
