### ISSUE TITLE
In-Reply-To / References

### ISSUE THREAD

**Issue by barryvdh** [beyondcode/laravel-mailbox#2]
So I was working on Inbound Email last week (what are the odds.. :P), mostly on the proper threading/matching of messages. I see that the `reply` here is pretty basic still, so would you be open to adding some more headers?

Basically the `In-Reply-To` header should use the `Message-ID` of the original message, and the `References` header should contain the IDs of all previous messages. This will help Gmail etc to match the threads (of the subject is different perhaps). 

Also, perhaps set the subject by default?

See for example https://github.com/fruitcake/php-inbound-mail/blob/1799148f2f6f8e4109e995be6849c389c1d3d81c/src/InboundMail.php#L11-L41

On the other way around, it might be useful to expose those headers, so it would be easier to 'thread' them? Eg. determine if it's a reply to a previous message.

**Comment by MatthewK177** [comment]
Where there any updates on this issue? I'm trying to figure out the best way to do threading but I'm unable to easily get the `In-Reply-To` ID.

**Comment by jhayg12** [comment]
Are there any updates on this? Currently having the same requirement for threading. Thanks

**Comment by adam-martinez** [comment]
2024 now and no movement on this? I can't set the "In-Reply-To" header because it says, 'Impossible to set header "In-Reply-To" as it's already defined and must be unique.'
