### ISSUE TITLE
Not really an issue more of a question

### ISSUE THREAD

**Issue by lstables** [beyondcode/laravel-mailbox#22]
Does the Mailbox package allow multiple emails?

Meaning within my application there could 1000s of users all with different emails they want to catch incoming and outgoing etc. 

Company A - may have X amount of users using companyA.com as their emails
Company B - may have X amount of users using companyB.com as their emails

Does the package allow for this?

**Comment by lstables** [comment]
@mpociot Can you shed some light on this for me, I did also tweet you yesterday.

**Comment by mpociot** [comment]
I’m not sure if I understand the exact use case. But you can define multiple mailboxes that will catch different emails. As long as you setup mailgun/sendgrid/whatever to send the emails that you want to match against.

**Comment by lstables** [comment]
Ok, thanks. I think that makes sense, basically my Laravel app will have multiple users that will belong to multiple companies. Thanks @mpociot
