### ISSUE TITLE
Possibility to use non-mime version for mailgun driver?

### ISSUE THREAD

**Issue by hailwood** [beyondcode/laravel-mailbox#28]
When you use an endpoint other than one ending in /mime mailgun sends across a bunch of really useful content in the request - e.g. "trimmed-text" which is the message text without any signatures or similar.

Unfortunately mailgun don't send this information when using a `/mime` endpoint and instead sends across "mime-body" which we're using to construct the message.

I'm not sure it would be possible but thought I'd float the idea of seeing if we can reconstruct the message from the extended mailgun information rather than the mime version which would give developers easy access to this additional information.

**Comment by vesper8** [comment]
Is this related to the error I'm getting a lot of `Invalid Mailgun signature or timestamp., Url:https://api.redacted.com/laravel-mailbox/mailgun/mime` ?

**Comment by dmyers** [comment]
@vesper8 Yes I believe so. Mailgun seems to have gotten rid of the `body-mime` option as part of the incoming email webhook as far as I can tell looking around, but it is available for stored messages, but this would require an additional step for routing and queue processing: https://documentation.mailgun.com/en/latest/api-sending.html#retrieving-stored-messages.

**Comment by dmyers** [comment]
@vesper8 Actually now I think Mailgun may have either changed the feature or this project didn't document it well.

It took me a while, but I found out some info from this page: https://documentation.mailgun.com/en/latest/user_manual.html#routes

Note To receive raw MIME messages and perform your own parsing you must configure a route with a URL ending with “mime”, like http://myhost/post_mime.

I just tried it and it worked for me by following that notice.

**Comment by vesper8** [comment]
thanks for the reply and the links @dmyers 

Can I ask what specifically are you doing to be able to receive mailgun messages into your laravel-mailbox? Did you set up webhooks or are you doing your own parsing?

I am using the suggested route which does end in /mime, so is it just then a matter of implementing my own parsing? How are you doing that? Would you mind sharing a snippet of code to help me going?

Thanks!

**Comment by vesper8** [comment]
@happyDemon it seems like the only thing you're doing different from me is that you renamed the default route from `laravel-mailbox/mailgun/mime` to `laravel-mailbox/mailgun/post_mime`

You think this made the difference? How did you rename the route by the way? I can't find anywhere in the documentation on where this default route is actually set and how to change it?

**Comment by vesper8** [comment]
actually.. I guess something must have changed because this was previously failing with an error and I just tried it again now, didn't have to rename the route or change anything at all and now it's working

**Comment by cihanarik** [comment]
Hi guys,
route defined in `vendor/beyondcode/laravel-mailbox/src/Drivers/Mailgun.php`
renaming default route from `laravel-mailbox/mailgun/mime` to `laravel-mailbox/mailgun/post_mime`
