### ISSUE TITLE
Visible Text

### ISSUE THREAD

**Issue by barryvdh** [beyondcode/laravel-mailbox#3]
You're currently using the Mime messages from Sendgrid/Mailgun I see, but Postmark has a nice feature called `StrippedTextReply`
See https://postmarkapp.com/developer/user-guide/inbound/parse-an-email

The PHP equivalent is https://github.com/willdurand/EmailReplyParser

So would you be interested in adding a  'visibleText' method that uses this? It would basically just be:
```php
function visibleText()
{
    return \EmailReplyParser\EmailReplyParser::parseReply($this->text());
}
```

**Comment by mpociot** [comment]
Hmm but what if an email only contains HTML content? Would it parse this too?

**Comment by barryvdh** [comment]
No I don't think so. But I wouldn't really know how you would process HTML only mails anyway. You can't really parse them, unless you convert them to text (which is difficult when you want to maintain the structure, as strip_tags probably won't make it very useful)

Don't most e-mail clients provide text version? Gmail, outlook etc?

**Comment by barryvdh** [comment]
Although there is this: https://github.com/soundasleep/html2text
Which could be used to automatically turn the HTML to Text, for example if you want to add comments to an issue etc.
