### ISSUE TITLE
Extending the package model to my own model

### ISSUE THREAD

**Issue by oliverbj** [beyondcode/laravel-mailbox#30]
Hi there

I can see that I can define a custom model to use in the config file:

```
    /*
     * The model class to use when converting an incoming email to a message.
     * It must extend the default model class
     */
    'model' => \BeyondCode\Mailbox\InboundEmail::class,
```
Above is the default model it uses.
I have changed it to:

```
    /*
     * The model class to use when converting an incoming email to a message.
     * It must extend the default model class
     */
    'model' => Email::class,
```

Now, I wish to use my own model, because I want to store the e-mails on another table. For this, I have created my own model:

App/Email.php:
```
namespace App;

use BeyondCode\Mailbox\InboundEmail as InboundEmail;

class Email extends InboundEmail
{
    protected $table = 'emails';
}
```

However, above gives me below error:
```
Undefined property: App\Email::$message {"exception":"[object] (ErrorException(code: 0): Undefined property: App\\Email::$message at /Users/Username/Sites/playground/vendor/beyondcode/laravel-mailbox/src/InboundEmail.php:130)
```

I suspect it is because I don't have the original methods in my own model `App/Email.php`, that are present in the package model.

Isn't there a way that I can use my own model, by extending the package model, but without copying the content of the package model into my own?

**Comment by chrisfritsche** [comment]
HI @oliverbj ! I try the same. I reply the model to my own model. But by retrieving the model by Nova, i receive the same error as you. Have you find any solution? 
Thanks for sharing.
