### ISSUE TITLE
[Question] How to test Mailbox in application?

### ISSUE THREAD

**Issue by radmen** [beyondcode/laravel-mailbox#34]
I'd like to add some tests for handling incoming emails.

How can I do it? Should I mock `Mailbox` facade, or just send some dummy requests to one of the incoming endpoints?

**Comment by RosiersRobin** [comment]
You can use the log env to send emails to any address.

So the 
`MAIL_DRIVER=log`
`MAILBOX_DRIVER=log`

variables are set like here.

Now when you make a route with the action like here:

```php
Mail::to('someone@whatever.tld')->send(new MyMail());
```

Then the email will be catched, when configured correctly.

**Comment by radmen** [comment]
@RosiersRobin thank you. Correct me if I'm wrong, yet it seems that this method is not usable in unit tests. This will print to log some data, yet it can't be used for assertions or mocking.

**Comment by RosiersRobin** [comment]
As far as I can see, the [nboundEmailTest.php](https://github.com/beyondcode/laravel-mailbox/blob/master/tests/InboundEmailTest.php) file does have tis implemented?

**Comment by radmen** [comment]
@RosiersRobin yup, that's it. Thanks!
