### ISSUE TITLE
Spam filtering

### ISSUE THREAD

**Issue by RosiersRobin** [beyondcode/laravel-mailbox#38]
Hi,

Is there any kind of inbound spam filtering? Since now when you do a catchall, the inbox is full of junk....

**Comment by julienbourdeau** [comment]
Have you checked if it was available by your email provider? What do you use?
This is probably out of scope for this package.

**Comment by RosiersRobin** [comment]
I'm using sendgrid as inbound parser, I have these both options enabled:

![screen](https://i.imgur.com/dDuKIs2.png), yet still I get alot of spam like showen here:

![spam](https://i.imgur.com/Gz14ksY.png)
![spam](https://i.imgur.com/NbR8gnn.png)

**Comment by RosiersRobin** [comment]
So my suggestion would be to add a spam score to the inbound eamail. Since that is added in the request payload .

>>> The spam checking doesn't block any messages from reaching your endpoint it just includes the spam_report and spam_score parameters within the payload.

**Comment by RosiersRobin** [comment]
Made PR #39

**Comment by mpociot** [comment]
I don't think a specific feature like this should be handled by this package. Like discussed in #39 we could pass the incoming raw request payload to the inbound email and then you can do whatever you want with it. Would you be up to create a PR for this?
