### ISSUE TITLE
Advice for extending

### ISSUE THREAD

**Issue by latwelve** [beyondcode/laravel-mailbox#65]
Hey - I started, extending this package into nova as a model and resource called Enquiry.. I needed some extra custom fields like "reference" "status" etc.. so I added these in the migration and started setting up the details and index views.. 

I've just come across an issue though when trying to save an Enquiry without any mail content:
Undefined property: App\Enquiry::$message
.../vendor/beyondcode/laravel-mailbox/src/InboundEmail.php#136

I just wanted to check am I extending this correctly? or would the neater behaviour have been to have a separate model / resource for Enquiry and set a relationship to a new Enquiry within the MyMailbox  __invoke ?

Thanks

**Comment by Norgul** [comment]
I'd say the `InboundEmail` class has wrong implementation in `message()` method because there is no `message` property. That's why you get an error. In your extended class, try to override the method and try again:

```
    public function message(): MimeMessage
    {
        return $this->mimeMessage;
    }
```
