### ISSUE TITLE
Running into error while installing mailbox in laravel 6

### ISSUE THREAD

**Issue by lyricsKING** [beyondcode/laravel-mailbox#66]
I'm running into error trying to install laravel-mailbox in my laravel 6 project using composer.
Below are the generated errors
` InvalidArgumentException  : Unable to resolve NULL driver for [BeyondCode\Mailbox\MailboxManager].

  at C:\wamp64\www\feedpal\vendor\laravel\framework\src\Illuminate\Support\Manager.php:81
    77|     {
    78|         $driver = $driver ?: $this->getDefaultDriver();
    79|
    80|         if (is_null($driver)) {
  > 81|             throw new InvalidArgumentException(sprintf(
    82|                 'Unable to resolve NULL driver for [%s].', static::class
    83|             ));
    84|         }
    85|

  Exception trace:

  1   Illuminate\Support\Manager::driver()
      C:\wamp64\www\feedpal\vendor\beyondcode\laravel-mailbox\src\MailboxManager.php:16

  2   BeyondCode\Mailbox\MailboxManager::mailbox()
      C:\wamp64\www\feedpal\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:23`

**Comment by lyricsKING** [comment]
i have managed to resolved this issue by removing the package and the manually copy the mailbox config file into my project's config folder
i then run
`php artisan config:cache`
and the 
`composer dump-autoload`
then install the package using composer and it worked.

**This line `C:\wamp64\www\feedpal\vendor\beyondcode\laravel-mailbox\src\MailboxManager.php:16` made a call to fetch the default driver for mailbox which at the point of installation was not set/availabe so manually copying the mailbox config file and before installing the package solved the issue for me **

**Comment by peterjaap** [comment]
I am also getting this issue on deployment. Can't clear the cache, can't do anything. I have no idea how to fix.

**Comment by Alyka** [comment]
I have the same issue
