### ISSUE TITLE
Installing Mailbox on Lumen 6

### ISSUE THREAD

**Issue by tony5Dim** [beyondcode/laravel-mailbox#67]
I can't install Mailbox on my Lumen 6 project.

Lumen doesn't automaticaly register the provider, then, I did a `$app->register(BeyondCode\Mailbox\MailboxServiceProvider::class);` in bootstrap/app.php.

But then I get the error 

> Call to undefined function BeyondCode\Mailbox\config_path()

So I've tried a solution found on the Internet https://gist.github.com/mabasic/21d13eab12462e596120
But then I get the error 

> Call to undefined method Laravel\Lumen\Routing\Router::aliasMiddleware()

I've also installed https://github.com/laravelista/lumen-vendor-publish to have access to `vendor:publish`

Now I can't do anything but uninstall all of theses...

**Comment by tony5Dim** [comment]
Nobody ?

**Comment by mpociot** [comment]
Laravel Mailbox does not currently support Lumen. If you can add it yourself, I would appreciate a PR.

**Comment by ayophanz** [comment]
try this `$this->app->alias('laravel-mailbox', MailboxBasicAuthentication::class);` update the serviceProvider in package
