### ISSUE TITLE
Testing driver

### ISSUE THREAD

**Issue by clementmas** [beyondcode/laravel-mailbox#72]
Hi there, thanks for the great package!

Is there a dedicated driver for testing?

```Supported drivers: "log", "mailgun", "sendgrid", "postmark"```

I'm currently using `log` but it logs all the emails every time I run my tests. It's not necessarily a bug but it's not ideal.

Is there some kind of in-memory `array` driver available or something similar?

Thanks!

**Comment by mpociot** [comment]
There's currently no `array` driver for testing available, but that would indeed be a cool idea. I'd accept a PR with it :)
