### ISSUE TITLE
Unable to resolve NULL driver

### ISSUE THREAD

**Issue by Norgul** [beyondcode/laravel-mailbox#73]
Hello,

I can require the package just fine, however when `dump-autoload` happens I am getting this error:

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException

  Unable to resolve NULL driver for [BeyondCode\Mailbox\MailboxManager].

  at vendor/laravel/framework/src/Illuminate/Support/Manager.php:71
     67▕     {
     68▕         $driver = $driver ?: $this->getDefaultDriver();
     69▕
     70▕         if (is_null($driver)) {
  ➜  71▕             throw new InvalidArgumentException(sprintf(
     72▕                 'Unable to resolve NULL driver for [%s].', static::class
     73▕             ));
     74▕         }
     75▕

      +13 vendor frames
  14  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

I am using `"laravel/framework": "^8.0"`.

I tried deleting lock files, vendor, clearing cache (wasn't cached initially), nothing happened.

Thanks

**Comment by Norgul** [comment]
My bad, it looks as if my environment was cached. `php artisan optimize:clear`, removed vendor and lock, reinstalled, works.

**Comment by yungkeatchan97** [comment]
I found another solution without removing the vendor folder:

1. Remove the cached file in `bootstrap/cache/config.php`
2. Copy `vendor/beyondcode/laravel-mailbox/config/mailbox.php` to `config/mailbox.php`
3. (Optional) Run `php artisan config:cache` to cache the configs back
