### ISSUE TITLE
SendGrid webhooks not resolving

### ISSUE THREAD

**Issue by dniccum** [beyondcode/laravel-mailbox#81]
Hi, I am currently migrating an application from using Mailgun to SendGrid. To be clear everything was working as desired using Mailgun, but as soon as I switched, nothing has worked since. The emails are clearly going somewhere because they are not being rejected. However the webhooks are not firing.

Any help would be appreciated.

I have followed everything in the documentation to a "T":

### My ENV variables

```dotenv
MAILBOX_DRIVER=sendgrid
MAILBOX_HTTP_PASSWORD=password
MAILBOX_DOMAIN="parse.mail.cultivateprm.com"
```

### Inbound Parse configuration

<img width="1339" alt="Screen Shot 2021-01-23 at 9 09 30 PM" src="https://user-images.githubusercontent.com/2816415/105620184-a1d29000-5dbf-11eb-84f6-05861c4f2a2a.png">

### DNS settings within GoDaddy

<img width="984" alt="Screen Shot 2021-01-23 at 9 11 39 PM" src="https://user-images.githubusercontent.com/2816415/105620185-a26b2680-5dbf-11eb-9612-e505d9107859.png">

**Comment by dniccum** [comment]
This issue was related to both my routes and configuration variables being cached. This has been resolved.

**Comment by ndcshuvro** [comment]
@dniccum I encounter with bad request while using as like your format. Can you help me for this.
