### ISSUE TITLE
Support in lumen

### ISSUE THREAD

**Issue by ayophanz** [beyondcode/laravel-mailbox#82]
I got error 500 in lumen

**Comment by ayophanz** [comment]
nvm I make it this works I just copy the package to my helper folder and modify the code to make it work in lumen

**Comment by goodevilgenius** [comment]
I think the main issue in Lumen is likely that some of the request types extend `FormRequest`, which is only in Laravel.

However, the dependencies don't actually state that Laravel is a dependency.

I think those requests don't actually need to inherit `FormRequest`. They should be able to just inherit `Request` without any other modification.
