### ISSUE TITLE
PHP 8 support (PR ready!! please accept)

### ISSUE THREAD

**Issue by basslhm** [beyondcode/laravel-mailbox#84]
Please just accept the following PR so that we can use this package with PHP 8

https://github.com/beyondcode/laravel-mailbox/pull/80

**Comment by colinmackinlay** [comment]
@sschlein @mpociot There are quite a few people asking for this #80. Even a response to say you've seen it and are reviewing would be appreciated :)

**Comment by colinmackinlay** [comment]
Thank you @mpociot :)

**Comment by atymic** [comment]
This can be closed cc @mpociot
